server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/myemployees?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
  thymeleaf:
    cache: false
  messages:
    basename: i18n/login
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

